name: CraftTown
version: 1.0
api-version: 1.19
main: elc.florian.Main
commands:
  alert:
    description: Envoie un alerte dans le chat
    aliases:
      - alerte
  city:
    description: Consulter la liste des villes
    aliases:
      - ville
  bridge:
    description: Set des blocks en dessous du joueur.
    aliases:
      - auto-bridge
